### ISSUE TITLE
Attachment error: TypeError: 'float' object is not subscriptable

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-AssemblyLine#409]
**Describe the bug**
```
TypeError: 'float' object is not subscriptable
```

**To Reproduce**
1. Upload zip file of package (provided below)
2. Put "0" in for every text field. Avoid other input, e.g. checkboxes.
3. Go as far as you can.
4. See error.

**Expected behavior**
Expected to get to the end of the interview

**Screenshots**

**Version Information (should be in `your.docassemble.server/updatepackage`:**
 - Docassemble Version: 1.3.21
 - AssemblyLine Version: 2.10.1

**Additional context**

I think this is related to ALDocument, specifically to overflow content. In the zip file attached below, I think the relevant .yml file line is:

```yml
  - MaineFeeWaiverFinancial_CV191_attachment: ALDocument.using(title="Maine CV 191 Affidavit in Support of Fee Waiver", filename="MaineFeeWaiverFinancial_CV191.pdf", enabled=True, has_addendum=True, default_overflow_message=AL_DEFAULT_OVERFLOW_MESSAGE)
```

Zip file of package that caused the error:
[docassemble-MainefeewaiverfinancialCv191.zip](https://github.com/SuffolkLITLab/docassemble-AssemblyLine/files/8134852/docassemble-MainefeewaiverfinancialCv191.zip)

Full traceback:
```
Log
Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7753, in assemble
    exec_with_trap(question, user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 9086, in exec_with_trap
    exec(the_question.compute, the_dict)
  File "<code block>", line 7, in <module>
NameError: name 'MaineFeeWaiverFinancial_CV191_preview_question' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/webapp/server.py", line 7555, in index
    interview.assemble(user_dict, interview_status, old_user_dict, force_question=special_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8032, in assemble
    raise the_error
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 7821, in assemble
    question_result = self.askfor(missingVariable, user_dict, old_user_dict, interview_status, seeking=interview_status.seeking, follow_mc=follow_mc, seeking_question=seeking_question)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 8515, in askfor
    return question.ask(user_dict, old_user_dict, the_x, iterators, missing_var, origMissingVariable)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 4953, in ask
    subquestion = self.subcontent.text(user_dict).rstrip()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/parse.py", line 1423, in text
    return self.template.render(**the_user_dict)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/template.py", line 451, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 828, in _render
    _render_context(template, callable_, context, *args,
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 864, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/base/mako/runtime.py", line 890, in _exec_template
    callable_(context, *args, **kwargs)
  File "memory:0x7f8fc12bcdc0", line 30, in render_body
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/AssemblyLine/al_document.py", line 906, in as_pdf
    pdf = files[0].as_pdf(key=key, refresh=refresh)
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/AssemblyLine/al_document.py", line 651, in as_pdf
    self.need_addendum()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/AssemblyLine/al_document.py", line 732, in need_addendum
    hasattr(self, "has_addendum") and self.has_addendum and self.has_overflow()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/AssemblyLine/al_document.py", line 736, in has_overflow
    return self.overflow_fields.has_overflow()
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/AssemblyLine/al_document.py", line 487, in has_overflow
    if field.overflow_value():
  File "/usr/share/docassemble/local3.8/lib/python3.8/site-packages/docassemble/AssemblyLine/al_document.py", line 169, in overflow_value
    return original_value[self.overflow_trigger :]
TypeError: 'float' object is not subscriptable
```

**Comment by BryceStevenWilley** [comment]
What interview are you finding this in?

**Comment by nonprofittechy** [comment]
Do you have a full stack trace? It looks like somewhere someone is adding a float to an addendum. Which doesn't make much sense but is probably easy to do accidentally if you just check the box in the Weaver. 

We could probably add some validation that prevents that combination in the Weaver. But I don't think this is a bug in Assembly Line.
