### ISSUE TITLE
Prod error: `other_parties` not defined

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/docassemble-AssemblyLine#707]
```
There was an error in the CourtFormsOnline application.

The error message was:

NameError: 

    NameError: name 'other_parties' is not defined

Traceback (most recent call last):
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 6904, in index
    exec(list_collect_list + '._allow_appending()', user_dict)
  File "", line 1, in 
NameError: name 'other_parties' is not defined

The referer URL was https://apps.suffolklitlab.org/run/indigency/
```

It says indigency, but other_parties is defined in here, so something weird is going on.

**Comment by nonprofittechy** [comment]
I think this is part of the weirdness with Jonathan changing the way some variables get triggered. Worth trying to upgrade to latest DA and see if the problem is reproducible
